theme: jekyll-theme-minimal


permalink: /:categories/:year/:month/:title/
title: Alexandre Symeonidis-Herzig's Project
description: A collection of things I've worked on (and the occasional picture of my cat)
